name: yamllint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install and run yamllint
      run: |
        pip install --user yamllint
        yamllint -d relaxed *.y*ml
        echo yamllint ends
