name: yamllint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install yamllint

    - name: Run yamllint
      env:
        COMMITS_CONTEXT: ${{ toJson(github.event.commits) }}
        FILES_MODIFIED: ${{ toJson(github.event.commits[0].modified) }}
        FILES_STRING: ${{ join(github.event.commits[0].modified) }}
      run: |
        yamllint -d "{extends: relaxed, rules:{trailing-spaces: disable, line-length: disable, indentation: disable, empty-lines: disable, commas: disable, colons: disable, hyphens: disable}}" $FILES_STRING
        echo yamllint ends
